### PR TITLE
Undraft the bylaws: Conflict of Interest Policy [due 2 Aug]

### PR DESCRIPTION
**Pull request by ebullient**
[🗳️ Vote progress](https://github.com/commonhaus/foundation/pull/177#issuecomment-2240507927 "IC_kwDOKRPTI86Fi3AX")

Continuing with our reviews: the Conflict of Interest policy.

voting group: @commonhaus/cf-egc 

Do one of the following:

- Approve the PR or react with 👍 (:+1:) if it looks good to you
- Review with Comments or react with 👀 (:eyes:) if you're "ok" with it (it may not be your favorite)
- If you think it needs discussion or revision
    - Create a review, add your comments and require changes
    - Use the +- button to make a suggestion (instead of just adding a comment).

### CODE REVIEW

**Review by henri-tremblay — COMMENTED** [review]
Do we define our voting process somewhere that will apply to conflict of interest? For instance, is it an hidden vote or an open one? Do we document who voted what?

**Review by evanchooly — APPROVED** [review]

**Comment by ebullient** [comment]
> Do we define our voting process somewhere that will apply to conflict of interest? For instance, is it an hidden vote or an open one? Do we document who voted what?

The vote is specifically for Councilors (the CFC) as the representatives with fiduciary responsibility. These votes would likely occur at a meeting, and would be recorded in the minutes.

**Review by aalmiray — APPROVED** [review]

**Review by cealsair — APPROVED** [review]

**Comment by ebullient** [comment]
extending deadline for detailed review

**Review by velo — APPROVED** [review]

**Review by marc0der — APPROVED** [review]

**Comment by ebullient** [comment]
vote::result no disagreement

**Pull request merged**
