### PR TITLE
📝 Undraft the bylaws: Advisory Board

### PR DESCRIPTION
**Pull request by ebullient**
[🗳️ Vote progress](https://github.com/commonhaus/foundation/pull/180#issuecomment-2260957720 "IC_kwDOKRPTI86Gw3oY")

Defining the role of the Advisory Board is one part of this. 

Edit: Tiers will be discussed/managed separately.

voting group: @commonhaus/cf-egc 

Do one of the following:

- Approve the PR or react with 👍 (:+1:) if it looks good to you
- Review with Comments or react with 👀 (:eyes:) if you're "ok" with it (it may not be your favorite)
- If you think it needs discussion or revision
    - Create a review, add your comments and require changes
    - Use the +- button to make a suggestion (instead of just adding a comment).

### CODE REVIEW

**Review by cealsair — APPROVED** [review]

**Comment by kenfinnigan** [comment]
Whether the sponsorship tiers belong in the by-laws for the advisory board probably depends on who is approving the tiers.

If only the Council approves the tiers, then it's external. If the whole EGC approves the tiers, maybe combine with by-laws to cover approval. Only thing I'm not sure about is whether changing the tiers, and thus by-laws, too frequently would be problematic at all

**Review by velo — APPROVED** [review]

**Comment by dandreadis** [comment]
I've 👍 for the changes but somewhat related, I was wondering if there are sponsoring requirements for companies to enter the Advisory Board with their representative(s).

**Comment by ebullient** [comment]
> Whether the sponsorship tiers belong in the by-laws for the advisory board probably depends on who is approving the tiers.
> 
> If only the Council approves the tiers, then it's external. If the whole EGC approves the tiers, maybe combine with by-laws to cover approval. Only thing I'm not sure about is whether changing the tiers, and thus by-laws, too frequently would be problematic at all

I don't think we need the tiers in the bylaws. We can still (via any other discussion) look for some consensus or input on tier structure. All of that said, at its core, the tier structure is an operational concern (it doesn't directly impact how projects are run).

**Comment by ebullient** [comment]
> I've 👍 for the changes but somewhat related, I was wondering if there are sponsoring requirements for companies to enter the Advisory Board with their representative(s).

Cynically, the requirement is some amount of 💰. Tiers coming soon.

**Review by evanchooly — APPROVED** [review]

**Comment by ebullient** [comment]
vote::result unanimous

**Pull request merged**
