### PR TITLE
Debezium bootstrapping agreement, 2024-10-30

### PR DESCRIPTION
**Pull request by Naros**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Is it only the main repo that wants to join Commonhaus Foundation, or all repos in the GH org?

**Comment by JooHyukKim** [comment]
> Is it only the main repo that wants to join Commonhaus Foundation, or all repos in the GH org?

Good question

**Comment by jpechane** [comment]
Sorry for the confusion, definitely all active repos. Just the one referred in the agreement is the main one.

**Comment by Naros** [comment]
Thanks @jpechane for clarifying.

**Review by gavinking — COMMENTED** [review]
Should Debezium also be added to the list of unregistered trademarks in `TRADEMARKS.md`?

**Comment by ebullient** [comment]
> Should Debezium also be added to the list of unregistered trademarks in `TRADEMARKS.md`?

yes. with or without a logo.

**Review by ebullient — APPROVED** [review]

**Comment by gunnarmorling** [comment]
@Naros, @ebullient, I am a bit confused by that boostrapping document, which appears to describe the bootstrapping process of the CH Foundation itself, rather than the process of moving Debezium to the same?

**Comment by ebullient** [comment]
> @Naros, @ebullient, I am a bit confused by that boostrapping document, which appears to describe the bootstrapping process of the CH Foundation itself, rather than the process of moving Debezium to the same?

Correct. Asset transfer and on-boarding processes are in progress.

**Pull request merged**
