### PR TITLE
Undraft the bylaws: Trademark Policy [due 17 Aug]

### PR DESCRIPTION
**Pull request by ebullient**
[🗳️ Vote progress](https://github.com/commonhaus/foundation/pull/179#issuecomment-2241183154 "IC_kwDOKRPTI86Flb2y")

Continuing with our reviews: the Trademark policy.

voting group: @commonhaus/cf-egc 

Do one of the following:

- Approve the PR or react with 👍 (:+1:) if it looks good to you
- Review with Comments or react with 👀 (:eyes:) if you're "ok" with it (it may not be your favorite)
- If you think it needs discussion or revision
    - Create a review, add your comments and require changes
    - Use the +- button to make a suggestion (instead of just adding a comment).

### CODE REVIEW

**Review by cealsair — APPROVED** [review]

**Review by jkschneider — CHANGES_REQUESTED** [review]
> Incorrect [CF Mark] by [your company name]

OpenRewrite objects to this constraint. I think it is incompatible with CommonHaus’ general policy that the foundation doesn’t interefere in the governance of projects. It is clear that Moderne is the governing maintainer of OpenRewrite (at the current time) regardless of who legally owns the trademark.

**Comment by ebullient** [comment]
> > Incorrect [CF Mark] by [your company name]
> 
> OpenRewrite objects to this constraint. I think it is incompatible with CommonHaus’ general policy that the foundation doesn’t interefere in the governance of projects. It is clear that Moderne is the governing maintainer of OpenRewrite (at the current time) regardless of who legally owns the trademark.

I'll ask some questions to make sure I understand the boundaries of this language.

**Comment by maxandersen** [comment]
I know why the "x by <company>" exist as problematic in other similar ones and that's because it makes it sound like X is provided by the company and only that company.

I'm wondering if "x sponsored by <company>" would work as that is less exclusive and more descriptive of the situation?

(IANAL :)

**Comment by ebullient** [comment]
> I know why the "x by " exist as problematic in other similar ones and that's because it makes it sound like X is provided by the company and only that company.
> 
> I'm wondering if "x sponsored by " would work as that is less exclusive and more descriptive of the situation?
> 
> (IANAL :)

Yes. This is right in-line with the questions I want to ask.

I am seeing some confusion, as this policy does not prohibit general usage of the marks, it only prohibits usage outside the guidelines of the policy.

> The use of the Mark cannot be used to imply that the Commonhaus Foundation or its projects are sponsoring or endorsing your product.

Note the directionality: Commonhaus/Project -> you/your product. 

> Do not use CF Marks (Logos or Word Marks) in any commercial or marketing context other than as expressly permitted in this policy unless you have obtained explicit written permission from the Commonhaus Foundation to do so.

"expressly permitted" is what we need to explore, but written permission should not be considered a barrier. We can create transparent/written agreements that make trademark ownership + allowed usage clear. CF has no reason to make it harder to talk about projects. The trick is ensuring that the trademark can be defended, and having permission in writing can help with that.

**Comment by ebullient** [comment]
extended deadline so we can think through options

**Comment by ebullient** [comment]
vote::result
I'm going to close this one for now, and re-open with revisions to address the concerns raised.

**Pull request closed without merging**
