### PR TITLE
Undraft the bylaws: indemnification and dissolution [due May 27]

### PR DESCRIPTION
**Pull request by kenfinnigan**
[🗳️ Vote progress](https://github.com/commonhaus/foundation/pull/161#issuecomment-2123267005 "IC_kwDOKRPTI85-jnu9")

Let's undraft the Insurance, Indemnification, and Dissolution policies.

voting group: @commonhaus/cf-egc 

Do one of the following:

- Approve the PR or react with 👍 (:+1:) if it looks good to you
- Review with Comments or react with 👀 (:eyes:) if you're "ok" with it (it may not be your favorite)
- If you think it needs discussion or revision
    - Create a review, add your comments and require changes
    - Use the +- button to make a suggestion (instead of just adding a comment).

### CODE REVIEW

**Review by ebullient — APPROVED** [review]

**Review by cowtowncoder — APPROVED** [review]

**Review by evanchooly — APPROVED** [review]

**Comment by gavinking** [comment]
> This indemnification does not extend to a person who is found liable in an action by the Foundation, or in right of the Foundation.

What does this sentence mean?

**Comment by ebullient** [comment]
> > This indemnification does not extend to a person who is found liable in an action by the Foundation, or in right of the Foundation.
> 
> What does this sentence mean?

This could be a better way to say it: 

This indemnification does not cover a person who is found responsible for wrongdoing in a legal action brought by the Foundation or on behalf of the Foundation.

Basically, if you are actually doing something unlawful, you are not covered by this.

If we want to revise this one, I'll have to check w/ the lawyer (not a big deal, just saying this is a section with legal-load-bearing words).

**Comment by gavinking** [comment]
Well it was a question. Consider:

> found liable in an action by the Foundation

probably this is something that any lawyer understands, but _I_ don't know what it means: what is an "action by the Foundation". From your reply it seems that means 

> found liable in a _legal_ action _brought_ by the Foundation

but to my nonlawyer eyes that wasn't clear at all.

And:

> or in right of the Foundation

just looks like there's some words missing (again to my nonlawer eyes).

**Comment by ebullient** [comment]
Noted. I'll ask. ;)

**Review by gavinking — APPROVED** [review]

**Review by gavinking — APPROVED** [review]

**Review by henri-tremblay — APPROVED** [review]

**Review by marc0der — APPROVED** [review]

**Review by cealsair — APPROVED** [review]

**Comment by ebullient** [comment]
vote::result 

Closed after good questions and unanimous consent

**Pull request merged**
